# Determinar libertad calculando cumulantes mixtos

En el caso libre, y valuado en operadores

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, transform

In [2]:
import sys
import os
parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.insert(0, parent_dir)

In [3]:
from Independence import Free_Independence, OV_Independence

## Checar si dos variables A y B son libres 

Calcular los cumulantes mixtos

In [4]:
# en el espacio de estas variables
# definir multiplicacion y funcional lineal

# funcional lineal
def phi(Z):
    return 1/N * Z.trace()
# multiplicacion
def multiply(Z1, Z2):
    return Z1 @ Z2

**Definir las variables A y B**

In [5]:
N = 100
M1 = 200
M2 = 100
aux1 = np.random.randn(N, M1)
aux2 = np.random.randn(N, M2)

In [6]:
# # definir las variables A y B
A = (aux1 @ aux1.T)/(M1*N)
B = (aux2 @ aux2.T)/(M2*N)

In [7]:
# # definir las variables A y B
# A = (aux1 @ aux1.T)/(M1)
# B = (aux2 @ aux2.T)/(M2)

In [8]:
# # definir las variables A y B
# A = (aux1 @ aux1.T)
# B = (aux2 @ aux2.T)

In [9]:
# calcular cumulantes mixtos de las variables
test = Free_Independence(A, B, functional_phi = phi, product = multiply)
res = test.check_mixed_cumulants(max_order = 6, print_results = True)

κ(('A', 'B')) = -1.5844233572214893e-06
κ(('A', 'A', 'B')) = -9.867540776954727e-09
κ(('A', 'B', 'B')) = -2.243803131899892e-08
κ(('A', 'A', 'A', 'B')) = -5.5987439130014136e-11
κ(('A', 'A', 'B', 'B')) = -1.4419713085157728e-10
κ(('A', 'B', 'A', 'B')) = -1.1316068509984697e-10
κ(('A', 'B', 'B', 'B')) = -3.0113641613303727e-10
κ(('A', 'A', 'A', 'A', 'B')) = -1.1174323879802605e-13
κ(('A', 'A', 'A', 'B', 'B')) = -9.509598937432747e-13
κ(('A', 'A', 'B', 'A', 'B')) = -1.717930707399043e-13
κ(('A', 'A', 'B', 'B', 'B')) = -7.23188189186033e-13
κ(('A', 'B', 'A', 'B', 'B')) = -1.4611140915195868e-12
κ(('A', 'B', 'B', 'B', 'B')) = -3.390063581247257e-12
κ(('A', 'A', 'A', 'A', 'A', 'B')) = 4.572051287388089e-16
κ(('A', 'A', 'A', 'A', 'B', 'B')) = -5.630723646961093e-15
κ(('A', 'A', 'A', 'B', 'A', 'B')) = 1.3895362367426274e-15
κ(('A', 'A', 'A', 'B', 'B', 'B')) = -8.901368255016521e-15
κ(('A', 'A', 'B', 'A', 'A', 'B')) = -2.984448090192385e-15
κ(('A', 'A', 'B', 'A', 'B', 'B')) = 4.538348108185328

**Comprobar que mi codigo calcule las cosas correctamente.**

In [10]:
# comprobar k(A, B)
print(phi(A @ B) - phi(A) * phi(B))
print(test.evaluate_cumulant(("A", "B")))

-1.5844233572214893e-06
-1.5844233572214893e-06


In [11]:
# comprobar k(A, B, A)
print(phi(A @ B @ A) - phi(A)*phi(A@B) - phi(A@B)*phi(A) - phi(A@A)*phi(B) + 2*phi(A)*phi(B)*phi(A))
print(test.evaluate_cumulant(("A", "B", "A")))

-9.867540776955045e-09
-9.867540776954727e-09


In [12]:
# comprobar k(B, A, B)
print(phi(B @ A @ B) - phi(B)*phi(B@A) - phi(B@A)*phi(B) - phi(B@B)*phi(A) + 2*phi(B)*phi(A)*phi(B))
print(test.evaluate_cumulant(("B", "A", "B")))

-2.243803131899937e-08
-2.243803131899892e-08


**Ver numeros de ejeucciones**

In [13]:
# ver cuantas evaluaciones de phi y de cumulantes
print(f"Evalauciones de cumulantes: {len(test.cumulant_evaluation)}")
print(f"Evalauciones de phi: {len(test.phi_evaluation)}")

Evalauciones de cumulantes: 35
Evalauciones de phi: 35


In [14]:
print(test.not_saved_cumulant_evaluation)
print(test.saved_cumulant_evaluation)

35
6771


## Checar si dos variables A y B son libres con amalgación

Calcular los cumulantes mixtos

In [15]:
N = 100

M1 = 200
M2 = 40
M3 = 60
M4 = 80

In [16]:
# gaussian NxM
aux1 = np.random.randn(N, M1)
aux2 = np.random.randn(N, M2)
aux3 = np.random.randn(N, M3)
aux4 = np.random.randn(N, M4)

# elementos
auxx1 = (aux1 @ aux1.T) / (M1*N)
auxx2 = (aux2 @ aux2.T) / (M2*N)
auxx3 = (aux3 @ aux3.T) / (M3*N)
auxx4 = (aux4 @ aux4.T) / (M4*N)

In [17]:
# elementos
auxx1 = (aux1 @ aux1.T) / (M1)
auxx2 = (aux2 @ aux2.T) / (M2)
auxx3 = (aux3 @ aux3.T) / (M3)
auxx4 = (aux4 @ aux4.T) / (M4)

In [18]:
# # elementos
# auxx1 = (aux1 @ aux1.T) 
# auxx2 = (aux2 @ aux2.T) 
# auxx3 = (aux3 @ aux3.T) 
# auxx4 = (aux4 @ aux4.T) 

In [19]:
# definir las variables A y B en formato que se pide para OV
A = {(1, 1): auxx1, (1, 2): auxx2, (2, 1): auxx2, (2, 2): auxx1}
B = {(1, 1): auxx3, (1, 2): auxx4, (2, 1): auxx4, (2, 2): auxx3}

# hacerlas como matrices a bloques para la comprobacion
matriz_A = np.block([[auxx1, auxx2], [auxx2, auxx1]])
matriz_B = np.block([[auxx3, auxx4], [auxx4, auxx3]])

In [20]:
# calcular cumulantes mixtos de las variables
ov_test = OV_Independence(A, B, d = 2, functional_phi = phi, product = multiply)
res = ov_test.check_mixed_cumulants(max_order = 6, print_results = True)

κ^(B)(('A', 'B')) = 
[[0.03692421 0.02940263]
 [0.02940263 0.03692421]]
--
κ^(B)(('B', 'A')) = 
[[0.03692421 0.02940263]
 [0.02940263 0.03692421]]
--
κ^(B)(('A', 'A', 'B')) = 
[[0.0637045  0.16732565]
 [0.16732565 0.0637045 ]]
--
κ^(B)(('A', 'B', 'A')) = 
[[0.0637045  0.16732565]
 [0.16732565 0.0637045 ]]
--
κ^(B)(('A', 'B', 'B')) = 
[[-0.03699519  0.13306767]
 [ 0.13306767 -0.03699519]]
--
κ^(B)(('B', 'A', 'A')) = 
[[0.0637045  0.16732565]
 [0.16732565 0.0637045 ]]
--
κ^(B)(('B', 'A', 'B')) = 
[[-0.03699519  0.13306767]
 [ 0.13306767 -0.03699519]]
--
κ^(B)(('B', 'B', 'A')) = 
[[-0.03699519  0.13306767]
 [ 0.13306767 -0.03699519]]
--
κ^(B)(('A', 'A', 'A', 'B')) = 
[[0.33563628 0.2627534 ]
 [0.2627534  0.33563628]]
--
κ^(B)(('A', 'A', 'B', 'A')) = 
[[0.33563628 0.2627534 ]
 [0.2627534  0.33563628]]
--
κ^(B)(('A', 'A', 'B', 'B')) = 
[[ 0.54478222 -0.08653526]
 [-0.08653526  0.54478222]]
--
κ^(B)(('A', 'B', 'A', 'A')) = 
[[0.33563628 0.2627534 ]
 [0.2627534  0.33563628]]
--
κ^(B)(('A', 'B

κ^(B)(('B', 'A', 'A', 'B', 'B', 'B')) = 
[[ 0.72613771 -2.20291394]
 [-2.20291394  0.72613771]]
--
κ^(B)(('B', 'A', 'B', 'A', 'A', 'A')) = 
[[-2.26045477  0.32968604]
 [ 0.32968604 -2.26045477]]
--
κ^(B)(('B', 'A', 'B', 'A', 'A', 'B')) = 
[[-0.08985111 -0.91526487]
 [-0.91526487 -0.08985111]]
--
κ^(B)(('B', 'A', 'B', 'A', 'B', 'A')) = 
[[-0.96777849 -0.07292454]
 [-0.07292454 -0.96777849]]
--
κ^(B)(('B', 'A', 'B', 'A', 'B', 'B')) = 
[[-0.16710513  0.43120753]
 [ 0.43120753 -0.16710513]]
--
κ^(B)(('B', 'A', 'B', 'B', 'A', 'A')) = 
[[-0.08985111 -0.91526487]
 [-0.91526487 -0.08985111]]
--
κ^(B)(('B', 'A', 'B', 'B', 'A', 'B')) = 
[[-0.62071597  0.90261054]
 [ 0.90261054 -0.62071597]]
--
κ^(B)(('B', 'A', 'B', 'B', 'B', 'A')) = 
[[-0.16710513  0.43120753]
 [ 0.43120753 -0.16710513]]
--
κ^(B)(('B', 'A', 'B', 'B', 'B', 'B')) = 
[[-0.61993564 -1.65122296]
 [-1.65122296 -0.61993564]]
--
κ^(B)(('B', 'B', 'A', 'A', 'A', 'A')) = 
[[3.09424441 2.48790873]
 [2.48790873 3.09424441]]
--
κ^(B)(('B', 'B

**Comprobar que mi codigo calcule las cosas correctamente.**

In [21]:
# Esperanza condicional: E = id tensor phi
def Esperanza_condicional(A):
    # esto es justamente F2
    assert A.shape == (2*N, 2*N)
    
    # sacar los 4 bloques de NxN
    A11 = A[0:N, 0:N]
    A12 = A[0:N, N:2*N]
    A21 = A[N:2*N, 0:N]
    A22 = A[N:2*N, N:2*N]
    # aplicar phi a cada uno
    # no multiplico por la identidad para que se vea mas bonito
    phi_A11 = phi(A11)
    phi_A12 = phi(A12)
    phi_A21 = phi(A21)
    phi_A22 = phi(A22)
    # juntar para crear el resultado
    return np.array([[phi_A11, phi_A12], [phi_A21, phi_A22]])

In [22]:
# comprobar k(A, B)
print(Esperanza_condicional(matriz_A @ matriz_B) - Esperanza_condicional(matriz_A) @ Esperanza_condicional(matriz_B))
print(ov_test.evaluate_ov_cumulant(("A", "B")))

[[0.03692421 0.02940263]
 [0.02940263 0.03692421]]
[[0.03692421 0.02940263]
 [0.02940263 0.03692421]]


In [23]:
# comprobar k(A, A)
print(Esperanza_condicional(matriz_A @ matriz_A) - Esperanza_condicional(matriz_A) @ Esperanza_condicional(matriz_A))
print(ov_test.evaluate_ov_cumulant(("A", "A")))

[[ 3.33176148 -0.00467679]
 [-0.00467679  3.33176148]]
[[ 3.33176148 -0.00467679]
 [-0.00467679  3.33176148]]


**Ver numeros de ejeucciones**

In [24]:
# ver cuantas evaluaciones de phi y de cumulantes
print(f"Evalauciones de operated-value cumulantes: {len(ov_test.ov_cumulant_evaluation)}")
print(f"Evalauciones de cumulantes: {len(ov_test.cumulant_evaluation)}")
print(f"Evalauciones de phi: {len(ov_test.phi_evaluation)}")

Evalauciones de operated-value cumulantes: 115
Evalauciones de cumulantes: 9114
Evalauciones de phi: 9114


In [25]:
# para los cumulantes operated value
print(ov_test.ov_saved_cumulant_evaluation)
print(ov_test.ov_not_saved_cumulant_evaluation)

1
115


In [26]:
# para los cumulantes en los bloques
print(ov_test.not_saved_cumulant_evaluation)
print(ov_test.saved_cumulant_evaluation)

9114
2585122


**Ver si las matrices a bloques son libres en el sentido escalar**

In [27]:
# redefinir (mas general)
def phi(Z):
    return 1/(Z.shape[0]) * Z.trace()

In [28]:
# calcular cumulantes mixtos de las matrices a bloques
test = Free_Independence(matriz_A, matriz_B, functional_phi = phi, product = multiply)
res = test.check_mixed_cumulants(max_order = 6, print_results = True)

κ(('A', 'B')) = 1.0920628246872548
κ(('A', 'A', 'B')) = 0.1204189633944992
κ(('A', 'B', 'B')) = -0.05312534387354484
κ(('A', 'A', 'A', 'B')) = 11.337810091992763
κ(('A', 'A', 'B', 'B')) = 0.1266106051537782
κ(('A', 'B', 'A', 'B')) = 6.015157383863778
κ(('A', 'B', 'B', 'B')) = 4.186423788211523
κ(('A', 'A', 'A', 'A', 'B')) = 2.635827874941505
κ(('A', 'A', 'A', 'B', 'B')) = -0.022725704785415246
κ(('A', 'A', 'B', 'A', 'B')) = 1.0872530833266936
κ(('A', 'A', 'B', 'B', 'B')) = -0.07881635308191809
κ(('A', 'B', 'A', 'B', 'B')) = 3.1134256313576643
κ(('A', 'B', 'B', 'B', 'B')) = 5.271749606048455
κ(('A', 'A', 'A', 'A', 'A', 'B')) = 159.9863119060992
κ(('A', 'A', 'A', 'A', 'B', 'B')) = -5.194376332724737
κ(('A', 'A', 'A', 'B', 'A', 'B')) = 50.24993593556749
κ(('A', 'A', 'A', 'B', 'B', 'B')) = 46.618089726705904
κ(('A', 'A', 'B', 'A', 'A', 'B')) = 27.90957876719069
κ(('A', 'A', 'B', 'A', 'B', 'B')) = -2.8501503628560516
κ(('A', 'A', 'B', 'B', 'A', 'B')) = -2.850150362856036
κ(('A', 'A', 'B', '